"""Reasoning and developer remediation data models for AccessLens AI.

Defines the structured ReasoningResult contract used by local reasoning engines
to explain deterministic accessibility findings without cloud dependencies.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


@dataclass
class ReasoningResult:
    """Structured, evidence-grounded reasoning result for an accessibility finding.
    
    The local reasoning engine provides contextual explanations, architectural impact,
    and developer remediation guidance grounded strictly in observed evidence.
    It does not modify the deterministic finding or claim compliance certification.
    """
    finding_id: str
    summary: str
    why_it_matters: str
    evidence_summary: str
    confidence_explanation: str
    remediation: str
    developer_actions: List[str] = field(default_factory=list)
    verification_steps: List[str] = field(default_factory=list)
    limitations: str = ""
    human_verification_required: bool = True
    evidence_references: List[str] = field(default_factory=list)
    generated_by: str = "Deterministic Local Reasoning"
    model_name: str = "AccessLens Rule-Based Remediation Engine"
    model_version: str = "1.0"
    runtime: str = "CPU"
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        """Serializes reasoning result to a dictionary representation."""
        return {
            "finding_id": self.finding_id,
            "summary": self.summary,
            "why_it_matters": self.why_it_matters,
            "evidence_summary": self.evidence_summary,
            "confidence_explanation": self.confidence_explanation,
            "remediation": self.remediation,
            "developer_actions": list(self.developer_actions),
            "verification_steps": list(self.verification_steps),
            "limitations": self.limitations,
            "human_verification_required": self.human_verification_required,
            "evidence_references": list(self.evidence_references),
            "generated_by": self.generated_by,
            "model_name": self.model_name,
            "model_version": self.model_version,
            "runtime": self.runtime,
            "timestamp": self.timestamp,
        }

    def to_developer_guidance_text(self) -> str:
        """Formats developer remediation into clean, shareable plain text."""
        lines = [
            f"=== AccessLens Developer Remediation Guidance ===",
            f"Finding ID: {self.finding_id}",
            f"Generated By: {self.generated_by} ({self.model_name} v{self.model_version} on {self.runtime})",
            "",
            "SUMMARY:",
            self.summary,
            "",
            "WHY IT MATTERS:",
            self.why_it_matters,
            "",
            "RECOMMENDED REMEDIATION:",
            self.remediation,
            "",
            "DEVELOPER ACTION STEPS:"
        ]
        for idx, action in enumerate(self.developer_actions, start=1):
            lines.append(f"  {idx}. {action}")
        
        lines.append("")
        lines.append("HUMAN VERIFICATION STEPS:")
        for idx, step in enumerate(self.verification_steps, start=1):
            lines.append(f"  [ ] Step {idx}: {step}")

        if self.limitations:
            lines.append("")
            lines.append(f"LIMITATIONS & CONTEXT:\n{self.limitations}")

        lines.append("")
        lines.append("NOTICE: Automated accessibility inspection assists QA and development. "
                     "Human verification is required for accessibility validation.")
        return "\n".join(lines)
